/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_idealismxxm_onlinejudge_judger_core_Compiler */

#ifndef _Included_cn_idealismxxm_onlinejudge_judger_core_Compiler
#define _Included_cn_idealismxxm_onlinejudge_judger_core_Compiler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_idealismxxm_onlinejudge_judger_core_Compiler
 * Method:    compile
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_idealismxxm_onlinejudge_judger_core_Compiler_compile
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
