/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_idealismxxm_onlinejudge_judger_core_Executor */

#ifndef _Included_cn_idealismxxm_onlinejudge_judger_core_Executor
#define _Included_cn_idealismxxm_onlinejudge_judger_core_Executor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_idealismxxm_onlinejudge_judger_core_Executor
 * Method:    execute
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_idealismxxm_onlinejudge_judger_core_Executor_execute
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jstring, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
